"""Replace V4/V5 replay layer payloads in place, with a backup.

The old layer sourceId and file name are retained so the website object-tree
entries are updated rather than duplicated.  The replacement payload is first
generated by the canonical Node importer and then its display name is refreshed
with the new conservative-stop-first metrics.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime
from pathlib import Path
from typing import Any


PROJECT = Path(__file__).resolve().parents[1]
LAYER_DIR = PROJECT / "src" / "data" / "replay-trade-layers"
REPO = Path(r"D:\项目\tradingview\.codex_checkpoint_repo")
OUTPUTS = REPO / "outputs"
STANDARD_ROOT = OUTPUTS / "v4_v5_structural_trailing_recalculation_20260816"
FAST_ROOT = OUTPUTS / "v4_v5_structural_trailing_recalculation_fast_20260816"
IMPORTER = PROJECT / "scripts" / "import-replay-layer.mjs"
NODE = Path(r"C:\Program Files\nodejs\node.exe")
BACKUP_ROOT = PROJECT / ".replay-layer-backups"


def read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def backtest_files(root: Path) -> list[Path]:
    if not root.is_dir():
        return []
    return [
        path
        for path in root.rglob("backtest.json")
        if path.is_file()
    ] + [
        path
        for path in root.rglob("fixed-risk-backtest.json")
        if path.is_file()
    ]


def old_parent_by_hash() -> dict[str, Path]:
    result: dict[str, Path] = {}
    for path in backtest_files(OUTPUTS):
        parent = path.parent
        if STANDARD_ROOT in path.parents or FAST_ROOT in path.parents:
            continue
        digest = sha256(path)
        result.setdefault(digest, parent)
    return result


def new_backtest_by_parent() -> dict[str, Path]:
    result: dict[str, Path] = {}
    for root in (STANDARD_ROOT, FAST_ROOT):
        for path in backtest_files(root):
            result[path.parent.name] = path
    return result


def format_usd(value: float) -> str:
    return f"+${value:,.2f}" if value >= 0 else f"-${abs(value):,.2f}"


def refreshed_name(old_name: str, backtest: dict[str, Any], trade_count: int) -> str:
    summary = backtest["scenarios"]["conservative_stop_first"]["summary"]
    closed = int(summary.get("closed_trades") or trade_count)
    wins = int(summary.get("winning_trades") or 0)
    win_rate = float(summary.get("win_rate_percent") or (wins * 100 / closed if closed else 0))
    risk_summary = summary.get("fixed_risk_usd") or {}
    pnl = float(risk_summary.get("net_pnl_usd") or 0)
    updated = re.sub(r"胜率[0-9]+(?:\.[0-9]+)?%", f"胜率{win_rate:.2f}%", old_name)
    updated = re.sub(r"净盈亏[+-]\$[0-9,]+(?:\.[0-9]+)?", f"净盈亏{format_usd(pnl)}", updated)
    if updated == old_name:
        updated = f"{old_name} 胜率{win_rate:.2f}% 净盈亏{format_usd(pnl)}"
    return updated


def run_importer(
    *,
    input_path: Path,
    signals_path: Path,
    name: str,
    output_path: Path | None,
    dry_run: bool,
) -> dict[str, Any]:
    command = [
        str(NODE),
        str(IMPORTER),
        "--project",
        str(PROJECT),
        "--input",
        str(input_path),
        "--signals",
        str(signals_path),
        "--name",
        name,
    ]
    if output_path is not None:
        command.extend(["--output", str(output_path)])
    if dry_run:
        command.append("--dry-run")
    completed = subprocess.run(command, check=False, capture_output=True, text=True, encoding="utf-8")
    if completed.returncode != 0:
        raise RuntimeError(
            f"importer failed for {input_path}:\n{completed.stdout}\n{completed.stderr}"
        )
    matches = re.findall(r"^IMPORT_RESULT (.+)$", completed.stdout, flags=re.MULTILINE)
    if not matches:
        raise RuntimeError(f"importer did not emit IMPORT_RESULT for {input_path}: {completed.stdout}")
    return json.loads(matches[-1])


def inventory() -> list[dict[str, Any]]:
    old_by_hash = old_parent_by_hash()
    new_by_parent = new_backtest_by_parent()
    rows: list[dict[str, Any]] = []
    for path in sorted(LAYER_DIR.glob("*.json")):
        payload = read_json(path)
        name = str(payload.get("layer", {}).get("name") or "")
        if not re.search(r"V[45]", name):
            continue
        old_hash = str(payload.get("provenance", {}).get("backtestSha256") or "")
        parent = old_by_hash.get(old_hash)
        if parent is None:
            raise RuntimeError(f"cannot map old layer to legacy backtest: {path.name}")
        input_path = new_by_parent.get(parent.name)
        if input_path is None:
            raise RuntimeError(f"no recalculated backtest for old layer {path.name} parent {parent.name}")
        signals_path = input_path.parent / "signals_with_trade_plans.json"
        if not signals_path.is_file():
            raise RuntimeError(f"missing recalculated signals for {input_path}")
        rows.append(
            {
                "target": path,
                "old_payload": payload,
                "old_hash": old_hash,
                "old_parent": parent,
                "input": input_path,
                "signals": signals_path,
            }
        )
    if len(rows) != 43:
        raise RuntimeError(f"expected 43 V4/V5 layers, found {len(rows)}")
    return rows


def prepare_rows(rows: list[dict[str, Any]], staging: Path, dry_run: bool) -> list[dict[str, Any]]:
    prepared: list[dict[str, Any]] = []
    for index, row in enumerate(rows):
        input_backtest = read_json(row["input"])
        name = refreshed_name(row["old_payload"]["layer"]["name"], input_backtest, 0)
        result = run_importer(
            input_path=row["input"],
            signals_path=row["signals"],
            name=name,
            output_path=None if dry_run else staging / f"{index:03d}.json",
            dry_run=dry_run,
        )
        row = dict(row)
        row.update({"new_name": name, "import_result": result})
        if not dry_run:
            staged = read_json(staging / f"{index:03d}.json")
            old_source_id = row["old_payload"]["layer"]["sourceId"]
            staged["layer"]["sourceId"] = old_source_id
            staged["layer"]["name"] = name
            row["replacement"] = staged
        prepared.append(row)
        print(
            json.dumps(
                {
                    "target": row["target"].name,
                    "parent": row["old_parent"].name,
                    "new_name": name,
                    "trades": result["trades"],
                    "dry_run": dry_run,
                },
                ensure_ascii=False,
            )
        )
    return prepared


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    if not NODE.is_file():
        raise FileNotFoundError(NODE)
    rows = inventory()
    with tempfile.TemporaryDirectory(prefix="v4-v5-layer-stage-") as temporary:
        prepared = prepare_rows(rows, Path(temporary), args.dry_run)
        if args.dry_run:
            print(json.dumps({"status": "dry_run_ok", "layers": len(prepared)}, ensure_ascii=False))
            return 0

        timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        backup = BACKUP_ROOT / f"v4-v5-structural-trailing-{timestamp}"
        backup.mkdir(parents=True, exist_ok=False)
        manifest_rows: list[dict[str, Any]] = []
        for row in prepared:
            target: Path = row["target"]
            backup_path = backup / target.name
            shutil.copy2(target, backup_path)
            replacement = row["replacement"]
            if replacement["layer"]["sourceId"] != row["old_payload"]["layer"]["sourceId"]:
                raise RuntimeError(f"sourceId preservation failed for {target.name}")
            target.write_text(json.dumps(replacement, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
            final = read_json(target)
            if final["layer"]["sourceId"] != row["old_payload"]["layer"]["sourceId"]:
                raise RuntimeError(f"post-write sourceId verification failed for {target.name}")
            if len(final["trades"]) != row["import_result"]["trades"]:
                raise RuntimeError(f"post-write trade count verification failed for {target.name}")
            manifest_rows.append(
                {
                    "target": str(target),
                    "backup": str(backup_path),
                    "sourceId": final["layer"]["sourceId"],
                    "oldBacktestSha256": row["old_hash"],
                    "newBacktestSha256": final["provenance"]["backtestSha256"],
                    "oldName": row["old_payload"]["layer"]["name"],
                    "newName": final["layer"]["name"],
                    "oldTrades": len(row["old_payload"]["trades"]),
                    "newTrades": len(final["trades"]),
                    "newExitReasonCounts": final["summary"]["exitReasonCounts"],
                }
            )
        write_json(
            backup / "replacement-manifest.json",
            {
                "status": "complete",
                "mode": "in_place_source_id_preserving_replacement",
                "layers": len(manifest_rows),
                "targets": manifest_rows,
            },
        )
        print(json.dumps({"status": "replaced", "layers": len(manifest_rows), "backup": str(backup)}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as error:
        print(f"ERROR: {error}", file=sys.stderr)
        raise
